# -*- coding: utf-8 -*-
"""
Setup Script for Distributed PFC Runs (HQH Working Condition)

This script prepares the necessary directory structure for the HQH 
distributed simulation run. It creates task pools (todo, running, done, failed)
and populates the 'todo' pool with all the configuration files
generated by 'parameter_sampler_hqh.py'.

It should be run ONLY ONCE on the main computer before starting any workers.
"""

import os
import shutil

# --- Configuration ---
# Directory containing the generated .json configuration files.
CONFIGS_SOURCE_DIR = "configs_to_run_hqh"  # <-- _MODIFIED_

# Names for the task state directories.
DIR_TODO = "jobs_todo"
DIR_RUNNING = "jobs_running"
DIR_DONE = "jobs_done"
DIR_FAILED = "jobs_failed"

def setup_distributed_run_hqh():
    """
    Main function to set up the directory structure for HQH distributed runs.
    """
    print("======================================================")
    print("      Setup for Distributed PFC Simulation (HQH)      ")
    print("======================================================")

    # 1. Create the necessary directories
    dirs_to_create = [DIR_TODO, DIR_RUNNING, DIR_DONE, DIR_FAILED]
    for directory in dirs_to_create:
        if not os.path.exists(directory):
            os.makedirs(directory)
            print(f"INFO: Created directory '{directory}'")
        else:
            print(f"INFO: Directory '{directory}' already exists.")

    # 2. Find all configuration files to be processed
    try:
        config_files = [f for f in os.listdir(CONFIGS_SOURCE_DIR) if f.endswith('.json')]
        if not config_files:
            print(f"WARNING: No configuration files found in '{CONFIGS_SOURCE_DIR}'. Nothing to do.")
            print("         Please run 'parameter_sampler_hqh.py' first.")
            return
    except FileNotFoundError:
        print(f"FATAL ERROR: Source directory '{CONFIGS_SOURCE_DIR}' not found.")
        print("Please run 'parameter_sampler_hqh.py' first to generate configurations.")
        return

    # 3. Copy config files to the 'jobs_todo' directory
    copied_count = 0
    for filename in config_files:
        source_path = os.path.join(CONFIGS_SOURCE_DIR, filename)
        destination_path = os.path.join(DIR_TODO, filename)
        
        # Copy only if it doesn't already exist, to avoid re-populating a partial run
        if not os.path.exists(destination_path):
            shutil.copy(source_path, destination_path)
            copied_count += 1

    print(f"\nINFO: Found {len(config_files)} total configurations in '{CONFIGS_SOURCE_DIR}'.")
    if copied_count > 0:
        print(f"INFO: Copied {copied_count} new configurations to '{DIR_TODO}'.")
    else:
        print(f"INFO: All configurations already exist in '{DIR_TODO}'. No new files were copied.")
        
    print("\nSUCCESS: Setup is complete. You can now start the worker.py script on any computer.")
    print("======================================================")


if __name__ == "__main__":
    setup_distributed_run_hqh()